# Generated by Django 2.2.1 on 2021-07-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210720_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user_rating_dict',
            field=models.CharField(default={}, max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
